### ISSUE TITLE
bug: Can't move back in download mode

### ISSUE THREAD

**Issue by RKulagin** [RKulagin/PKMS#8]
```
cd ../
Traceback (most recent call last):
  File "script.py", line 17, in <module>
    api.DownloadScript()
  File "/home/ruslan/Downloads/PKMS-dev/APIClass.py", line 78, in DownloadScript
    if int(number) >= len(list_of_data[0]):
ValueError: invalid literal for int() with base 10: '../'
```

**Comment by RKulagin** [comment]
From home directory
``` 
cd ..
Traceback (most recent call last):
  File "script.py", line 21, in <module>
    api.DownloadScript()
  File "/home/ruslan/Downloads/PKMS-dev/APIClass.py", line 104, in DownloadScript
    trash, number =  req.split()
ValueError: too many values to unpack (expected 2)
```

**Comment by RKulagin** [comment]
```
cd 0
cdd МГТУ им. Н. Э. Баумана
 0
d Алгебра
d Анализ и Синтез Конечных Автоматов
d Безопасность Систем Баз Данных
d Электроника и Схемотехника
cd 0
d Книги
d Лекции Д.А.Жукова
cd 1
f 0 algebra01_2021_handout.pdf 302.69 KB 2022-06-23T12:52:57+00:00
f 1 algebra02_2021_handout.pdf 177.09 KB 2022-06-23T12:52:57+00:00
f 2 algebra03_2021_handout.pdf 242.75 KB 2022-06-23T12:52:57+00:00
f 3 algebra04_2021_handout.pdf 311.34 KB 2022-06-23T12:52:58+00:00
f 4 algebra05_2022_handout.pdf 268.74 KB 2022-06-23T12:52:58+00:00
f 5 algebra06_2021_handout.pdf 183.04 KB 2022-06-23T12:52:58+00:00
f 6 algebra07_2021_handout.pdf 317.41 KB 2022-06-23T12:52:59+00:00
f 7 algebra08_2022_handout.pdf 317.96 KB 2022-06-23T12:52:59+00:00
f 8 algebra09_2022_handout.pdf 238.87 KB 2022-06-23T12:52:59+00:00
f 9 algebra10_2022_handout.pdf 321.82 KB 2022-06-23T12:53:00+00:00
f 10 algebra11_2022_handout.pdf 332.17 KB 2022-06-23T12:53:01+00:00
f 11 algebra12_2022_handout.pdf 367.08 KB 2022-06-23T12:53:01+00:00
f 12 algebra13_2022_handout.pdf 302.69 KB 2022-06-23T12:53:01+00:00
f 13 algebra14_2022_handout.pdf 208.63 KB 2022-06-23T12:53:01+00:00
get 3
[+] Downloading file algebra04_2021_handout.pdf from algebra04_2021_handout
[+] Processing...
[+] File algebra04_2021_handout.pdf downloaded successfully
cd ..
f 0 algebra01_2021_handout.pdf 302.69 KB 2022-06-23T12:52:57+00:00
f 1 algebra02_2021_handout.pdf 177.09 KB 2022-06-23T12:52:57+00:00
f 2 algebra03_2021_handout.pdf 242.75 KB 2022-06-23T12:52:57+00:00
f 3 algebra04_2021_handout.pdf 311.34 KB 2022-06-23T12:52:58+00:00
f 4 algebra05_2022_handout.pdf 268.74 KB 2022-06-23T12:52:58+00:00
f 5 algebra06_2021_handout.pdf 183.04 KB 2022-06-23T12:52:58+00:00
f 6 algebra07_2021_handout.pdf 317.41 KB 2022-06-23T12:52:59+00:00
f 7 algebra08_2022_handout.pdf 317.96 KB 2022-06-23T12:52:59+00:00
f 8 algebra09_2022_handout.pdf 238.87 KB 2022-06-23T12:52:59+00:00
f 9 algebra10_2022_handout.pdf 321.82 KB 2022-06-23T12:53:00+00:00
f 10 algebra11_2022_handout.pdf 332.17 KB 2022-06-23T12:53:01+00:00
f 11 algebra12_2022_handout.pdf 367.08 KB 2022-06-23T12:53:01+00:00
f 12 algebra13_2022_handout.pdf 302.69 KB 2022-06-23T12:53:01+00:00
f 13 algebra14_2022_handout.pdf 208.63 KB 2022-06-23T12:53:01+00:00
cd ..
d Книги
d Лекции Д.А.Жукова
cd 1
something goes wrong : 404
Resource not found.
```

После команды get ожидается продолжение работы программы, при этом выполнение продолжается из той же папки, в которой был произведён get
